
package soap.wizard.wsdl.classes;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Server", targetNamespace = "http://service.soap/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Server {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getServerName", targetNamespace = "http://service.soap/", className = "soap.wizard.wsdl.classes.GetServerName")
    @ResponseWrapper(localName = "getServerNameResponse", targetNamespace = "http://service.soap/", className = "soap.wizard.wsdl.classes.GetServerNameResponse")
    @Action(input = "http://service.soap/Server/getServerNameRequest", output = "http://service.soap/Server/getServerNameResponse")
    public String getServerName();

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Double
     * @throws SecretException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calculator", targetNamespace = "http://service.soap/", className = "soap.wizard.wsdl.classes.Calculator")
    @ResponseWrapper(localName = "calculatorResponse", targetNamespace = "http://service.soap/", className = "soap.wizard.wsdl.classes.CalculatorResponse")
    @Action(input = "http://service.soap/Server/calculatorRequest", output = "http://service.soap/Server/calculatorResponse", fault = {
        @FaultAction(className = SecretException_Exception.class, value = "http://service.soap/Server/calculator/Fault/SecretException")
    })
    public Double calculator(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Double arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        Double arg2)
        throws SecretException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getReverseMessage", targetNamespace = "http://service.soap/", className = "soap.wizard.wsdl.classes.GetReverseMessage")
    @ResponseWrapper(localName = "getReverseMessageResponse", targetNamespace = "http://service.soap/", className = "soap.wizard.wsdl.classes.GetReverseMessageResponse")
    @Action(input = "http://service.soap/Server/getReverseMessageRequest", output = "http://service.soap/Server/getReverseMessageResponse")
    public String getReverseMessage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
