
package soap.wizard.wsdl.classes;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Server", targetNamespace = "http://service.soap/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Server {


    /**
     * 
     * @param arg0
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "downloadImage", targetNamespace = "http://service.soap/", className = "soap.wizard.wsdl.classes.DownloadImage")
    @ResponseWrapper(localName = "downloadImageResponse", targetNamespace = "http://service.soap/", className = "soap.wizard.wsdl.classes.DownloadImageResponse")
    @Action(input = "http://service.soap/Server/downloadImageRequest", output = "http://service.soap/Server/downloadImageResponse")
    public byte[] downloadImage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "echo", targetNamespace = "http://service.soap/", className = "soap.wizard.wsdl.classes.Echo")
    @ResponseWrapper(localName = "echoResponse", targetNamespace = "http://service.soap/", className = "soap.wizard.wsdl.classes.EchoResponse")
    @Action(input = "http://service.soap/Server/echoRequest", output = "http://service.soap/Server/echoResponse")
    public String echo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
