
package soap.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "SecretException", targetNamespace = "http://service.soap/")
public class SecretException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SecretException faultInfo;

    /**
     *
     * @param message
     */
    public SecretException_Exception(String message) {
        super(message);
        this.faultInfo = new SecretException();
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public SecretException_Exception(String message, SecretException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: soap.service.SecretException
     */
    public SecretException getFaultInfo() {
        return faultInfo;
    }

}
